package top.wuhaojie.zhd.constant;

/**
 * Author: wuhaojie
 * E-mail: w19961009@126.com
 * Date: 2017/02/16 00:33
 * Version: 1.0
 */

public interface Constants {


    String INTENT_EXTRA_STORY_IDS = "INTENT_EXTRA_STORY_IDS";
    String INTENT_EXTRA_STORY_CURRENT_ID = "INTENT_EXTRA_STORY_CURRENT_ID";
    String INTENT_EXTRA_IMAGE_URL = "INTENT_EXTRA_IMAGE_URL";
    String INTENT_EXTRA_STORY_ID = "INTENT_EXTRA_STORY_ID";
    String INTENT_EXTRA_COMMENT_NUMBER = "INTENT_EXTRA_COMMENT_NUMBER";

    int CACHE_TYPE_LATEST_MESSAGES = 1;
    int CACHE_TYPE_DETAIL_MESSAGE = 2;
    int CACHE_TYPE_BEFORE_MESSAGE = 3;
    int CACHE_TYPE_SPLASH_TAG = 4;
    int CACHE_TYPE_THEME_LIST = 5;
}
