package top.wuhaojie.zhd.data.dto;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import top.wuhaojie.zhd.data.dto.WebCache;

import top.wuhaojie.zhd.data.dto.WebCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig webCacheDaoConfig;

    private final WebCacheDao webCacheDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        webCacheDaoConfig = daoConfigMap.get(WebCacheDao.class).clone();
        webCacheDaoConfig.initIdentityScope(type);

        webCacheDao = new WebCacheDao(webCacheDaoConfig, this);

        registerDao(WebCache.class, webCacheDao);
    }
    
    public void clear() {
        webCacheDaoConfig.getIdentityScope().clear();
    }

    public WebCacheDao getWebCacheDao() {
        return webCacheDao;
    }

}
